# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: selfagency
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: America/New_York
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_gists_limit: 5
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 300
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 365
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 32
          plugin_people_size: 32
          plugin_people_identicons: no
          plugin_people_shuffle: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 1
          plugin_stackoverflow_lines.snippet: 1
          plugin_stackoverflow_lines: 1
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_stackoverflow_user: 1857453
          plugin_stars: yes
          plugin_stars_limit: 5
          plugin_traffic: yes
